<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-android</TargetFramework>
        <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <WarningAsError>false</WarningAsError>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        
        <PackageId>Omnicasa.Mobile.Zetes.Droid</PackageId>
        <Version>0.0.0.1</Version>
        <Authors>HoangQuach</Authors>
        <Company>Omnicasa</Company>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <RepositoryUrl>https://github.com/omnicasa/Omnicasa.Mobile.Zetes</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>
</Project>