<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0-android;net8.0-ios;</TargetFrameworks>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">13.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>

        <PackageId>Omnicasa.Mobile.Zetes</PackageId>
        <Version>0.0.0.1</Version>
        <Authors>HoangQuach</Authors>
        <Company>Omnicasa</Company>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <RepositoryUrl>https://github.com/omnicasa/Omnicasa.Mobile.Zetes</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
        <PackageReference Include="Omnicasa.Analyzers" Version="2024.5.17.13" />
        <PackageReference Include="System.Reactive" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
      <PackageReference Include="Omnicasa.Mobile.Zetes.iOS" Version="2025.11.19.9-alpha" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android'">
      <PackageReference Include="Omnicasa.Mobile.Zetes.Droid" Version="2025.11.19.9-alpha" />
    </ItemGroup>
</Project>
